---

- name: NETCONF set NTP server
  hosts: iosxe
  gather_facts: false

  tasks:

    - name: Set subnet_id from selection or random value from 1 to 255
      ansible.builtin.set_fact:
        subnet_id: "{{ 1 + 255 | random }}"
      when:
        - subnet_id is not defined
          or
          subnet_id == "<REPLACE WITH INTEGER 0-254>"

    - name: Set NTP server
      ansible.netcommon.netconf_config:
        content: |
              <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
                <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
                  <ntp>
                    <server xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ntp">
                      <server-list>
                        <ip-address>10.1.{{ subnet_id }}.1</ip-address>
                      </server-list>
                    </server>
                  </ntp>
                </native>
              </config>

...
